export const books = [
  {
    book: "Genesis",
    bookShort: "Gen",
    verses: 1533,
    chapters: 50,
  },
  {
    book: "Exodus",
    bookShort: "Ex",
    verses: 1213,
    chapters: 40,
  },
  {
    book: "Leviticus",
    bookShort: "Lev",
    verses: 859,
    chapters: 27,
  },
  {
    book: "Numbers",
    bookShort: "Num",
    verses: 1288,
    chapters: 36,
  },
  {
    book: "Deuteronomy",
    bookShort: "Deut",
    verses: 959,
    chapters: 34,
  },
  {
    book: "Joshua",
    bookShort: "Josh",
    verses: 658,
    chapters: 24,
  },
  {
    book: "Judges",
    bookShort: "Judg",
    verses: 618,
    chapters: 21,
  },
  {
    book: "Ruth",
    bookShort: "Ruth",
    verses: 85,
    chapters: 4,
  },
  {
    book: "1 Samuel",
    bookShort: "1Sam",
    verses: 810,
    chapters: 31,
  },
  {
    book: "2 Samuel",
    bookShort: "2Sam",
    verses: 695,
    chapters: 24,
  },
  {
    book: "1 Kings",
    bookShort: "1Kings",
    verses: 816,
    chapters: 22,
  },
  {
    book: "2 Kings",
    bookShort: "2Kings",
    verses: 719,
    chapters: 25,
  },
  {
    book: "1 Chronicles",
    bookShort: "1Chron",
    verses: 942,
    chapters: 29,
  },
  {
    book: "2 Chronicles",
    bookShort: "2Chron",
    verses: 822,
    chapters: 36,
  },
  {
    book: "Ezra",
    bookShort: "Ezra",
    verses: 280,
    chapters: 10,
  },
  {
    book: "Nehemiah",
    bookShort: "Neh",
    verses: 406,
    chapters: 13,
  },
  {
    book: "Esther",
    bookShort: "Est",
    verses: 167,
    chapters: 10,
  },
  {
    book: "Job",
    bookShort: "Job",
    verses: 1070,
    chapters: 42,
  },
  {
    book: "Psalms",
    bookShort: "Ps",
    verses: 2461,
    chapters: 150,
  },
  {
    book: "Proverbs",
    bookShort: "Prov",
    verses: 915,
    chapters: 31,
  },
  {
    book: "Ecclesiastes",
    bookShort: "Eccles",
    verses: 222,
    chapters: 12,
  },
  {
    book: "Song of Solomon",
    bookShort: "Song",
    verses: 117,
    chapters: 8,
  },
  {
    book: "Isaiah",
    bookShort: "Isa",
    verses: 1292,
    chapters: 66,
  },
  {
    book: "Jeremiah",
    bookShort: "Jer",
    verses: 1364,
    chapters: 52,
  },
  {
    book: "Lamentations",
    bookShort: "Lam",
    verses: 154,
    chapters: 5,
  },
  {
    book: "Ezekiel",
    bookShort: "Ezek",
    verses: 1273,
    chapters: 48,
  },
  {
    book: "Daniel",
    bookShort: "Dan",
    verses: 357,
    chapters: 12,
  },
  {
    book: "Hosea",
    bookShort: "Hos",
    verses: 197,
    chapters: 14,
  },
  {
    book: "Joel",
    bookShort: "Joel",
    verses: 73,
    chapters: 3,
  },
  {
    book: "Amos",
    bookShort: "Amos",
    verses: 146,
    chapters: 9,
  },
  {
    book: "Obadiah",
    bookShort: "Obad",
    verses: 21,
    chapters: 1,
  },
  {
    book: "Jonah",
    bookShort: "Jonah",
    verses: 48,
    chapters: 4,
  },
  {
    book: "Micah",
    bookShort: "Mic",
    verses: 105,
    chapters: 7,
  },
  {
    book: "Nahum",
    bookShort: "Nah",
    verses: 47,
    chapters: 3,
  },
  {
    book: "Habakkuk",
    bookShort: "Hab",
    verses: 56,
    chapters: 3,
  },
  {
    book: "Zephaniah",
    bookShort: "Zeph",
    verses: 53,
    chapters: 3,
  },
  {
    book: "Haggai",
    bookShort: "Hag",
    verses: 38,
    chapters: 2,
  },
  {
    book: "Zechariah",
    bookShort: "Zech",
    verses: 211,
    chapters: 14,
  },
  {
    book: "Malachi",
    bookShort: "Mal",
    verses: 55,
    chapters: 4,
  },
  {
    book: "Matthew",
    bookShort: "Matt",
    verses: 1071,
    chapters: 28,
  },
  {
    book: "Mark",
    bookShort: "Mark",
    verses: 678,
    chapters: 16,
  },
  {
    book: "Luke",
    bookShort: "Luke",
    verses: 1151,
    chapters: 24,
  },
  {
    book: "John",
    bookShort: "John",
    verses: 879,
    chapters: 21,
  },
  {
    book: "Acts",
    bookShort: "Acts",
    verses: 1007,
    chapters: 28,
  },
  {
    book: "Romans",
    bookShort: "Rom",
    verses: 433,
    chapters: 16,
  },
  {
    book: "1 Corinthians",
    bookShort: "1Cor",
    verses: 437,
    chapters: 16,
  },
  {
    book: "2 Corinthians",
    bookShort: "1Cor",
    verses: 257,
    chapters: 13,
  },
  {
    book: "Galatians",
    bookShort: "Gal",
    verses: 149,
    chapters: 6,
  },
  {
    book: "Ephesians",
    bookShort: "Eph",
    verses: 155,
    chapters: 6,
  },
  {
    book: "Philippians",
    bookShort: "Phil",
    verses: 104,
    chapters: 4,
  },
  {
    book: "Colossians",
    bookShort: "Col",
    verses: 95,
    chapters: 4,
  },
  {
    book: "1 Thessalonians",
    bookShort: "1Thess",
    verses: 89,
    chapters: 5,
  },
  {
    book: "2 Thessalonians",
    bookShort: "2Thess",
    verses: 47,
    chapters: 3,
  },
  {
    book: "1 Timothy",
    bookShort: "1Tim",
    verses: 133,
    chapters: 6,
  },
  {
    book: "2 Timothy",
    bookShort: "2Tim",
    verses: 83,
    chapters: 4,
  },
  {
    book: "Titus",
    bookShort: "Titus",
    verses: 46,
    chapters: 3,
  },
  {
    book: "Philemon",
    bookShort: "Philem",
    verses: 25,
    chapters: 1,
  },
  {
    book: "Hebrews",
    bookShort: "Heb",
    verses: 303,
    chapters: 13,
  },
  {
    book: "James",
    bookShort: "James",
    verses: 108,
    chapters: 5,
  },
  {
    book: "1 Peter",
    bookShort: "1Pet",
    verses: 105,
    chapters: 5,
  },
  {
    book: "2 Peter",
    bookShort: "2Pet",
    verses: 61,
    chapters: 3,
  },
  {
    book: "1 John",
    bookShort: "1John",
    verses: 105,
    chapters: 5,
  },
  {
    book: "2 John",
    bookShort: "2John",
    verses: 13,
    chapters: 1,
  },
  {
    book: "3 John",
    bookShort: "3John",
    verses: 14,
    chapters: 1,
  },
  {
    book: "Jude",
    bookShort: "Jude",
    verses: 25,
    chapters: 1,
  },
  {
    book: "Revelation",
    bookShort: "Rev",
    verses: 404,
    chapters: 22,
  },
];

export type CategorizedBooks = {
  [category: string]: Array<{
    book: string;
    bookShort: string;
    verses: number;
    chapters: number;
  }>;
};

export const categorizedBooks: CategorizedBooks = {
  Pentateuch: [
    { book: "Genesis", verses: 1533, chapters: 50, bookShort: "Gen" },
    { book: "Exodus", verses: 1213, chapters: 40, bookShort: "Ex" },
    { book: "Leviticus", verses: 859, chapters: 27, bookShort: "Lev" },
    { book: "Numbers", verses: 1288, chapters: 36, bookShort: "Num" },
    { book: "Deuteronomy", verses: 959, chapters: 34, bookShort: "Deut " },
  ],
  "Old Testament Historical Books": [
    { book: "Joshua", verses: 658, chapters: 24, bookShort: "Josh" },
    { book: "Judges", verses: 618, chapters: 21, bookShort: "Judg" },
    { book: "Ruth", verses: 85, chapters: 4, bookShort: "Ruth" },
    { book: "1 Samuel", verses: 810, chapters: 31, bookShort: "1Sam" },
    { book: "2 Samuel", verses: 695, chapters: 24, bookShort: "2Sam" },
    { book: "1 Kings", verses: 816, chapters: 22, bookShort: "1Kings" },
    { book: "2 Kings", verses: 719, chapters: 25, bookShort: "2Kings" },
    { book: "1 Chronicles", verses: 942, chapters: 29, bookShort: "1Chron" },
    { book: "2 Chronicles", verses: 822, chapters: 36, bookShort: "2Chron" },
    { book: "Ezra", verses: 280, chapters: 10, bookShort: "Ezra" },
    { book: "Nehemiah", verses: 406, chapters: 13, bookShort: "Neh" },
    { book: "Esther", verses: 167, chapters: 10, bookShort: "Est" },
  ],
  "Wisdom Literature": [
    { book: "Job", verses: 1070, chapters: 42, bookShort: "Job" },
    { book: "Psalms", verses: 2461, chapters: 150, bookShort: "Ps" },
    { book: "Proverbs", verses: 915, chapters: 31, bookShort: "Prov" },
    { book: "Ecclesiastes", verses: 222, chapters: 12, bookShort: "Eccles" },
    { book: "Song of Solomon", verses: 117, chapters: 8, bookShort: "Song" },
  ],
  Prophets: [
    { book: "Isaiah", verses: 1292, chapters: 66, bookShort: "Isa" },
    { book: "Jeremiah", verses: 1364, chapters: 52, bookShort: "Jer" },
    { book: "Lamentations", verses: 154, chapters: 5, bookShort: "Lam" },
    { book: "Ezekiel", verses: 1273, chapters: 48, bookShort: "Ezek" },
    { book: "Daniel", verses: 357, chapters: 12, bookShort: "Dan" },
    { book: "Hosea", verses: 197, chapters: 14, bookShort: "Hos" },
    { book: "Joel", verses: 73, chapters: 3, bookShort: "Joel" },
    { book: "Amos", verses: 146, chapters: 9, bookShort: "Amos" },
    { book: "Obadiah", verses: 21, chapters: 1, bookShort: "Obad" },
    { book: "Jonah", verses: 48, chapters: 4, bookShort: "Jonah" },
    { book: "Micah", verses: 105, chapters: 7, bookShort: "Mic" },
    { book: "Nahum", verses: 47, chapters: 3, bookShort: "Nah" },
    { book: "Habakkuk", verses: 56, chapters: 3, bookShort: "Hab" },
    { book: "Zephaniah", verses: 53, chapters: 3, bookShort: "Zeph" },
    { book: "Haggai", verses: 38, chapters: 2, bookShort: "Hag" },
    { book: "Zechariah", verses: 211, chapters: 14, bookShort: "Zech" },
    { book: "Malachi", verses: 55, chapters: 4, bookShort: "Mal" },
  ],

  Gospels: [
    { book: "Matthew", verses: 1071, chapters: 28, bookShort: "Matt" },
    { book: "Mark", verses: 678, chapters: 16, bookShort: "Mark" },
    { book: "Luke", verses: 1151, chapters: 24, bookShort: "Luke" },
    { book: "John", verses: 879, chapters: 21, bookShort: "John" },
  ],
  "New Testament Historical Books": [
    { book: "Acts", verses: 1007, chapters: 28, bookShort: "Acts" },
  ],
  "Pauline Epistles": [
    { book: "Romans", verses: 433, chapters: 16, bookShort: "Rom" },
    { book: "1 Corinthians", verses: 437, chapters: 16, bookShort: "1Cor" },
    { book: "2 Corinthians", verses: 257, chapters: 13, bookShort: "2Cor" },
    { book: "Galatians", verses: 149, chapters: 6, bookShort: "Gal" },
    { book: "Ephesians", verses: 155, chapters: 6, bookShort: "Eph" },
    { book: "Philippians", verses: 104, chapters: 4, bookShort: "Phil" },
    { book: "Colossians", verses: 95, chapters: 4, bookShort: "Col" },
    { book: "1 Thessalonians", verses: 89, chapters: 5, bookShort: "1Thess" },
    { book: "2 Thessalonians", verses: 47, chapters: 3, bookShort: "2Thess" },
    { book: "1 Timothy", verses: 133, chapters: 6, bookShort: "1Tim" },
    { book: "2 Timothy", verses: 83, chapters: 4, bookShort: "2Tim" },
    { book: "Titus", verses: 46, chapters: 3, bookShort: "Titus" },
    { book: "Philemon", verses: 25, chapters: 1, bookShort: "Philem" },
  ],
  "General Epistles": [
    { book: "Hebrews", verses: 303, chapters: 13, bookShort: "Heb" },
    { book: "James", verses: 108, chapters: 5, bookShort: "James" },
    { book: "1 Peter", verses: 105, chapters: 5, bookShort: "1Pet" },
    { book: "2 Peter", verses: 61, chapters: 3, bookShort: "2Pet" },
    { book: "1 John", verses: 105, chapters: 5, bookShort: "1John" },
    { book: "2 John", verses: 13, chapters: 1, bookShort: "2John" },
    { book: "3 John", verses: 14, chapters: 1, bookShort: "3John" },
    { book: "Jude", verses: 25, chapters: 1, bookShort: "Jude" },
  ],
  Revelation: [
    { book: "Revelation", verses: 404, chapters: 22, bookShort: "Rev" },
  ],
};
